name: analysis

on: workflow_dispatch

permissions:
  contents: read
  security-events: write

jobs:
  analysis-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: analysis/analysis.sarif